### ISSUE TITLE
Image Not being added to db

### ISSUE THREAD

**Issue by ghost** [sivaprasadreddy/jcart#7]
Hi,

Thanks for this great project.

I have installed this project on my machine locally and it is working well fine.
But I have one issue.

When creating a new product the creation goes on successfully but the image url location is not added to the database.

Kindly help

**Comment by sivaprasadreddy** [comment]
Currently the path where the images will be stored is hard coded (D:/jcart/products) in WebUtils.java. Can you verify is that folder exists, otherwise change the path to some existing folder and check?

**Comment by ghost** [comment]
Hello Siva,
Suppose i wish to store products images in the db without hard coding their path. How can i go about it?

I will highly appreciate if you could provide a sample code for the same

**Comment by ungtq0805** [comment]
Dear Mr/Ms @LoneLeaner 
I appreciate that your idea, so I think you should convert the image into binary data and save it into DB.
This is the sample with Postgres, please prefer it
-> https://www.postgresql.org/docs/7.4/static/jdbc-binary-data.html

@sivaprasadreddy : Many thanks for you about this project. I am working on it and I saw that I've learned many things about you. 

Thanks and best regards
Tran Quoc Ung
