### ISSUE TITLE
Problem in Accessing

### ISSUE THREAD

**Issue by the-codingguy** [sivaprasadreddy/jcart#9]
Unable to run the code.
asking for password to unlock certicate/key storage

**Comment by sivaprasadreddy** [comment]
The credentials are there in application-default.properties file.

**Comment by hafssaeloiaabane** [comment]
how i can import your database ,i'm beginner in spriing can u help me plzzz

**Comment by hafssaeloiaabane** [comment]
unable to run the code when i write mvn spring-boot:run they give me command not found but i install it ,i don't know where is the problem

**Comment by sivaprasadreddy** [comment]
Please follow this https://maven.apache.org/install.html to setup maven properly.
